<a href="https://colab.research.google.com/github/jennharw/gitPractice/blob/main/Keyword_extraction_with_dic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files 
uploaded = files.upload()
import pandas as pd

Saving test.xlsx to test.xlsx

In [ ]:
eng = pd.read_pickle('clarivate_dictionary_v1.pickle')

In [ ]:
ed = pd.read_pickle('kci_dictionary_v2.pickle')

In [ ]:
!pip install konlpy

Collecting konlpy
  Downloading konlpy-0.5.2-py2.py3-none-any.whl (19.4 MB)
     |████████████████████████████████| 19.4 MB 3.7 MB/s
Collecting JPype1>=0.7.0
  Downloading JPype1-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (448 kB)
     |████████████████████████████████| 448 kB 36.7 MB/s
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.2.6)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting beautifulsoup4==4.6.0
  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 3.7 MB/s
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.19.5)
Requirement already satisfied: tweepy>=3.7.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (3.10.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (3.7.4.3)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from tweepy>=3.7.0->konlpy) (1.3.0)
Requirement already satisfied: requests[socks]>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from tweepy>=3.7.0->konlpy) (2.23.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from tweepy>=3.7.0->konlpy) (1.15.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->tweepy>=3.7.0->konlpy) (3.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (1.24.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (1.7.1)
Installing collected packages: JPype1, colorama, beautifulsoup4, konlpy
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed JPype1-1.3.0 beautifulsoup4-4.6.0 colorama-0.4.4 konlpy-0.5.2

In [ ]:
from konlpy.tag import Hannanum

In [ ]:
h = Hannanum()
hlist = h.nouns("황순원 문학의 시원에 시가 자리한다. 시인에서 소설가로 변신한 황순원의 문학적 이력은 그의 단편소설을 논의하는 자리에서 주목되었다. 서정성을 황순원 단편소설의 개성이라고 강조하는 논의들이 지속적으로 제출되었다. 그런데 서정성은 단편소설의 주요 속성이므로 황순원 단편소설의 개성으로 서정성을 지목하는 것은 당연한 사실을 특별한 것처럼 말하는 격이 된다. 서정의 보편적 면모들을 열거하면서 황순원 단편소설의 개성이라고 주장하는 것도 그 단편소설의 개성을 희석시키는 결과를 빚는다. 본 논문은 선행연구의 그러한 오류를 반성하면서 황순원 단편소설의 서정성이 지닌 고유한 개성을 주술적 초월과 회화적 서사로서 설명하고자 한다.전래서사의 주술적 효과는 황순원 단편소설의 중요한 구성 요소로서 기능한다. 전래서사가 직접 인용되지 않는 경우에도 주술적 효과가 삽화로서 서사에 복무하거나 더 나아가 서사의 구성 원리가 되기도 한다. 경험 현실이 주술적으로 이해되기도 하고 현실의 고통을 주술로써 초월하려는 시도도 보인다. 제의의 방식으로 서사가 짜이기도 한다. 인상적인 장면으로 서술을 대신하는 방법도 황순원의 단편소설에서 자주 사용된다. 장면이 그 전후의 서사적 전개를 집약하는 현상을 가리켜 본 논문은 회화적 서사로 명명하였다. 서사의 통시적 전개가 회화적 현재로 수렴된다는 점에서 회화적 서사는 황순원 단편소설의 서정성에 복무한다.서정은 주관 지향적이어서 현실의 객관적 재현을 위한 방법이 되기 어렵다. 현실 재현에 관한 한 황순원의 단편소설도 그러한 일반론에서 예외가 아니다. 그의 단편소설에서는 개관적 현실보다 현실에 대한 주관적 태도들이 재현된다. 황순원 단편소설의 작중인물들이 현실에 대해 취하는 태도는 인정주의와 인고에서 시작하여 허무주의가 드러나는 지점까지 진행한다.")

In [ ]:
hlist

['황순원',
 '문학',
 '시원',
 '시',
 '자리한다',
 '시인',
 '소설가',
 '변신',
 '황순원',
 '문학적',
 '이력',
 '그',
 '단편소설',
 '논의',
 '자리',
 '주목',
 '서정성',
 '황순원',
 '단편소설',
 '개성',
 '강조',
 '논의들',
 '지속적',
 '제출',
 '서정성',
 '단편소설',
 '주요',
 '속성',
 '황순원',
 '단편소설',
 '개성',
 '서정성',
 '지목',
 '것',
 '당연',
 '사실',
 '특별',
 '것',
 '말',
 '격',
 '서정',
 '보편적',
 '면모들',
 '열거',
 '황순원',
 '단편소설',
 '개성',
 '주장',
 '것',
 '단편소설',
 '개성',
 '희석',
 '결과',
 '논문',
 '선행연구',
 '오류',
 '반성',
 '황순원',
 '단편소설',
 '서정성',
 '고유',
 '개성',
 '주술적',
 '초월',
 '회화적',
 '서사',
 '설명',
 '전래서사',
 '주술적',
 '효과',
 '황순원',
 '단편소설',
 '중요',
 '구성',
 '요소',
 '기능한다',
 '전래서사',
 '인용',
 '경우',
 '주술적',
 '효과',
 '삽화',
 '서사',
 '복무',
 '서사',
 '구성',
 '원리',
 '경험',
 '현실',
 '주술적',
 '이해',
 '현실',
 '고통',
 '주술',
 '초월',
 '시',
 '제의',
 '방식',
 '서사',
 '짜',
 '인상적',
 '장면',
 '서술',
 '대신',
 '방법',
 '황순원',
 '단편소설',
 '사용',
 '장면',
 '전후',
 '서사적',
 '전개',
 '집약',
 '현상',
 '논문',
 '회화적',
 '서사',
 '명명',
 '서사',
 '통시적',
 '전개',
 '회화적',
 '현재',
 '수렴',
 '점',
 '회화적',
 '서사',
 '황순원',
 '단편소설',
 '서정성',
 '복무',
 '서정',
 '주관',
 '지향적',
 '현실',
 '객관적',
 '재현',
 '방법',
 '현실',
 '재현',
 '한',
 '황순원',
 '단편소설',
 '일반론',
 '예외',
 '그',
 '단편소설',
 '개관적',
 '현실',
 '현실',
 '주관적',
 '태도들',
 '재현',
 '황순원',
 '단편소설',
 '작중인물들',
 '현실',
 '태도',
 '인정주의',
 '인고',
 '시작',
 '허무주의',
 '지점',
 '진행']

In [ ]:
for i in range(len(hlist)-1):
   p = hlist[i] + " "+ hlist[i+1]
   hlist.append(p)

In [ ]:
hlist

['황순원',
 '문학',
 '시원',
 '시',
 '자리한다',
 '시인',
 '소설가',
 '변신',
 '황순원',
 '문학적',
 '이력',
 '그',
 '단편소설',
 '논의',
 '자리',
 '주목',
 '서정성',
 '황순원',
 '단편소설',
 '개성',
 '강조',
 '논의들',
 '지속적',
 '제출',
 '서정성',
 '단편소설',
 '주요',
 '속성',
 '황순원',
 '단편소설',
 '개성',
 '서정성',
 '지목',
 '것',
 '당연',
 '사실',
 '특별',
 '것',
 '말',
 '격',
 '서정',
 '보편적',
 '면모들',
 '열거',
 '황순원',
 '단편소설',
 '개성',
 '주장',
 '것',
 '단편소설',
 '개성',
 '희석',
 '결과',
 '논문',
 '선행연구',
 '오류',
 '반성',
 '황순원',
 '단편소설',
 '서정성',
 '고유',
 '개성',
 '주술적',
 '초월',
 '회화적',
 '서사',
 '설명',
 '전래서사',
 '주술적',
 '효과',
 '황순원',
 '단편소설',
 '중요',
 '구성',
 '요소',
 '기능한다',
 '전래서사',
 '인용',
 '경우',
 '주술적',
 '효과',
 '삽화',
 '서사',
 '복무',
 '서사',
 '구성',
 '원리',
 '경험',
 '현실',
 '주술적',
 '이해',
 '현실',
 '고통',
 '주술',
 '초월',
 '시',
 '제의',
 '방식',
 '서사',
 '짜',
 '인상적',
 '장면',
 '서술',
 '대신',
 '방법',
 '황순원',
 '단편소설',
 '사용',
 '장면',
 '전후',
 '서사적',
 '전개',
 '집약',
 '현상',
 '논문',
 '회화적',
 '서사',
 '명명',
 '서사',
 '통시적',
 '전개',
 '회화적',
 '현재',
 '수렴',
 '점',
 '회화적',
 '서사',
 '황순원',
 '단편소설',
 '서정성',
 '복무',
 '서정',
 '주관',
 '지향적',
 '현실',
 '객관적',
 '재현',
 '방법',
 '현실',
 '재현',
 '한',
 '황순원',
 '단편소설',
 '일반론',
 '예외',
 '그',
 '단편소설',
 '개관적',
 '현실',
 '현실',
 '주관적',
 '태도들',
 '재현',
 '황순원',
 '단편소설',
 '작중인물들',
 '현실',
 '태도',
 '인정주의',
 '인고',
 '시작',
 '허무주의',
 '지점',
 '진행',
 '황순원 문학',
 '문학 시원',
 '시원 시',
 '시 자리한다',
 '자리한다 시인',
 '시인 소설가',
 '소설가 변신',
 '변신 황순원',
 '황순원 문학적',
 '문학적 이력',
 '이력 그',
 '그 단편소설',
 '단편소설 논의',
 '논의 자리',
 '자리 주목',
 '주목 서정성',
 '서정성 황순원',
 '황순원 단편소설',
 '단편소설 개성',
 '개성 강조',
 '강조 논의들',
 '논의들 지속적',
 '지속적 제출',
 '제출 서정성',
 '서정성 단편소설',
 '단편소설 주요',
 '주요 속성',
 '속성 황순원',
 '황순원 단편소설',
 '단편소설 개성',
 '개성 서정성',
 '서정성 지목',
 '지목 것',
 '것 당연',
 '당연 사실',
 '사실 특별',
 '특별 것',
 '것 말',
 '말 격',
 '격 서정',
 '서정 보편적',
 '보편적 면모들',
 '면모들 열거',
 '열거 황순원',
 '황순원 단편소설',
 '단편소설 개성',
 '개성 주장',
 '주장 것',
 '것 단편소설',
 '단편소설 개성',
 '개성 희석',
 '희석 결과',
 '결과 논문',
 '논문 선행연구',
 '선행연구 오류',
 '오류 반성',
 '반성 황순원',
 '황순원 단편소설',
 '단편소설 서정성',
 '서정성 고유',
 '고유 개성',
 '개성 주술적',
 '주술적 초월',
 '초월 회화적',
 '회화적 서사',
 '서사 설명',
 '설명 전래서사',
 '전래서사 주술적',
 '주술적 효과',
 '효과 황순원',
 '황순원 단편소설',
 '단편소설 중요',
 '중요 구성',
 '구성 요소',
 '요소 기능한다',
 '기능한다 전래서사',
 '전래서사 인용',
 '인용 경우',
 '경우 주술적',
 '주술적 효과',
 '효과 삽화',
 '삽화 서사',
 '서사 복무',
 '복무 서사',
 '서사 구성',
 '구성 원리',
 '원리 경험',
 '경험 현실',
 '현실 주술적',
 '주술적 이해',
 '이해 현실',
 '현실 고통',
 '고통 주술',
 '주술 초월',
 '초월 시',
 '시 제의',
 '제의 방식',
 '방식 서사',
 '서사 짜',
 '짜 인상적',
 '인상적 장면',
 '장면 서술',
 '서술 대신',
 '대신 방법',
 '방법 황순원',
 '황순원 단편소설',
 '단편소설 사용',
 '사용 장면',
 '장면 전후',
 '전후 서사적',
 '서사적 전개',
 '전개 집약',
 '집약 현상',
 '현상 논문',
 '논문 회화적',
 '회화적 서사',
 '서사 명명',
 '명명 서사',
 '서사 통시적',
 '통시적 전개',
 '전개 회화적',
 '회화적 현재',
 '현재 수렴',
 '수렴 점',
 '점 회화적',
 '회화적 서사',
 '서사 황순원',
 '황순원 단편소설',
 '단편소설 서정성',
 '서정성 복무',
 '복무 서정',
 '서정 주관',
 '주관 지향적',
 '지향적 현실',
 '현실 객관적',
 '객관적 재현',
 '재현 방법',
 '방법 현실',
 '현실 재현',
 '재현 한',
 '한 황순원',
 '황순원 단편소설',
 '단편소설 일반론',
 '일반론 예외',
 '예외 그',
 '그 단편소설',
 '단편소설 개관적',
 '개관적 현실',
 '현실 현실',
 '현실 주관적',
 '주관적 태도들',
 '태도들 재현',
 '재현 황순원',
 '황순원 단편소설',
 '단편소설 작중인물들',
 '작중인물들 현실',
 '현실 태도',
 '태도 인정주의',
 '인정주의 인고',
 '인고 시작',
 '시작 허무주의',
 '허무주의 지점',
 '지점 진행']

In [ ]:
for i in range(len(ed)):
  ed0.update(set(ed[i]['keywords_df'].keys()))

In [ ]:
len(ed0)

1250678

In [ ]:
[word for word in hlist if word in ed0]

['황순원',
 '문학',
 '시원',
 '시',
 '시인',
 '소설가',
 '변신',
 '황순원',
 '문학적',
 '이력',
 '그',
 '단편소설',
 '논의',
 '자리',
 '주목',
 '서정성',
 '황순원',
 '단편소설',
 '개성',
 '강조',
 '지속적',
 '제출',
 '서정성',
 '단편소설',
 '속성',
 '황순원',
 '단편소설',
 '개성',
 '서정성',
 '지목',
 '것',
 '당연',
 '사실',
 '특별',
 '것',
 '말',
 '격',
 '서정',
 '보편적',
 '열거',
 '황순원',
 '단편소설',
 '개성',
 '주장',
 '것',
 '단편소설',
 '개성',
 '희석',
 '결과',
 '논문',
 '선행연구',
 '오류',
 '반성',
 '황순원',
 '단편소설',
 '서정성',
 '고유',
 '개성',
 '주술적',
 '초월',
 '회화적',
 '서사',
 '설명',
 '주술적',
 '효과',
 '황순원',
 '단편소설',
 '중요',
 '구성',
 '요소',
 '인용',
 '경우',
 '주술적',
 '효과',
 '삽화',
 '서사',
 '복무',
 '서사',
 '구성',
 '원리',
 '경험',
 '현실',
 '주술적',
 '이해',
 '현실',
 '고통',
 '주술',
 '초월',
 '시',
 '제의',
 '방식',
 '서사',
 '장면',
 '서술',
 '대신',
 '방법',
 '황순원',
 '단편소설',
 '사용',
 '장면',
 '전후',
 '서사적',
 '전개',
 '집약',
 '현상',
 '논문',
 '회화적',
 '서사',
 '명명',
 '서사',
 '통시적',
 '전개',
 '회화적',
 '현재',
 '수렴',
 '점',
 '회화적',
 '서사',
 '황순원',
 '단편소설',
 '서정성',
 '복무',
 '서정',
 '주관',
 '지향적',
 '현실',
 '객관적',
 '재현',
 '방법',
 '현실',
 '재현',
 '한',
 '황순원',
 '단편소설',
 '예외',
 '그',
 '단편소설',
 '현실',
 '현실',
 '주관적',
 '재현',
 '황순원',
 '단편소설',
 '현실',
 '태도',
 '인정주의',
 '인고',
 '시작',
 '허무주의',
 '지점',
 '진행',
 '황순원 단편소설',
 '주요 속성',
 '황순원 단편소설',
 '황순원 단편소설',
 '황순원 단편소설',
 '주술적 효과',
 '황순원 단편소설',
 '구성 요소',
 '주술적 효과',
 '서사 구성',
 '구성 원리',
 '황순원 단편소설',
 '서사적 전개',
 '황순원 단편소설',
 '현실 재현',
 '황순원 단편소설',
 '황순원 단편소설']

In [ ]:
#한글은 띄어쓰기 제외
#영어는 n gram

In [ ]:
x = ['machine','machine learning','an input',
 'an output',
 'based on',
 'example input',
 'function that',
 'input output',
 'input to',
 'is the',
 'learning function',
 'learning'
 'learning is',
 'learning task',
 
 'maps an',
 'of learning',
 'on example',
 'output based',
 'output pairs',
 'supervised learning',
 'task of',
 'that maps',
 'the machine',
 'to an']

In [ ]:
x[:10] + x[11:], x[10]

(['machine',
  'machine learning',
  'an input',
  'an output',
  'based on',
  'example input',
  'function that',
  'input output',
  'input to',
  'is the',
  'learninglearning is',
  'learning task',
  'maps an',
  'of learning',
  'on example',
  'output based',
  'output pairs',
  'supervised learning',
  'task of',
  'that maps',
  'the machine',
  'to an'],
 'learning function')

In [ ]:
y =  x[:10] + x[11:]

In [ ]:
y

['machine',
 'machine learning',
 'an input',
 'an output',
 'based on',
 'example input',
 'function that',
 'input output',
 'input to',
 'is the',
 'learninglearning is',
 'learning task',
 'maps an',
 'of learning',
 'on example',
 'output based',
 'output pairs',
 'supervised learning',
 'task of',
 'that maps',
 'the machine',
 'to an']

In [ ]:
x[10]  in ' '.join(y)

False

In [ ]:
x.remove(x[10])

In [ ]:
x

['machine learning',
 'an input',
 'an output',
 'based on',
 'example input',
 'function that',
 'input output',
 'input to',
 'is the',
 'learning function',
 'learning is',
 'learning task',
 'maps an',
 'of learning',
 'on example',
 'output based',
 'output pairs',
 'supervised learning',
 'task of',
 'that maps',
 'the machine',
 'to an']

In [ ]:
import pandas as pd
df = pd.read_excel('test.xlsx')

In [ ]:
filtered_words = list(filter(lambda word: ' ' in word, words))

In [ ]:
words_2 = ['deep', 'learning', 'deep learning', 'social','science', 'social psychology', 'meaning', 'sense']
words = ['deep', 'learning', 'deep learning', 'social','science', 'social psychology', 'meaning', 'sense']

filtered_words = list(filter(lambda word: ' ' in word, words))

for i in range(len(words)):
    for j in range(len(filtered_words)):
        if words[i] in filtered_words[j]:
            words_2.remove(words[i])


filtered_words.extend(words_2)


filtered_words

In [ ]:
i = df['content']
df['content2'] = i

In [ ]:
filtered_words = list(filter(lambda word: ' ' in word, df['content'][0]))

for i in range(len(df['content'][0])):
    for j in range(len(filtered_words)):
        if df['content'][0][i] in filtered_words[j]:
            df['content2'][0].remove(df['content'][0][i])


filtered_words.extend(df['content2'][0])


filtered_words

['[',
 "'",
 'd',
 'e',
 'e',
 'p',
 "'",
 ',',
 '\xa0',
 "'",
 'l',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 "'",
 ',',
 '\xa0',
 "'",
 'd',
 'e',
 'e',
 'p',
 '\xa0',
 'l',
 'e',
 'a',
 'r',
 'n',
 'i',
 'n',
 'g',
 "'",
 ',',
 '\xa0',
 "'",
 's',
 'o',
 'c',
 'i',
 'a',
 'l',
 "'",
 ',',
 "'",
 's',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 "'",
 ',',
 '\xa0',
 "'",
 's',
 'o',
 'c',
 'i',
 'a',
 'l',
 '\xa0',
 'p',
 's',
 'y',
 'c',
 'h',
 'o',
 'l',
 'o',
 'g',
 'y',
 "'",
 ',',
 '\xa0',
 "'",
 'm',
 'e',
 'a',
 'n',
 'i',
 'n',
 'g',
 "'",
 ',',
 '\xa0',
 "'",
 's',
 'e',
 'n',
 's',
 'e',
 "'",
 ']']

In [ ]:
len(ed)

251

In [ ]:
df = pd.read_excel('test.xlsx')
df.head()

  title                                             content
0      a   Supervised learning is the machine learning t...
1      b  In supervised learning, eac algorithm analyzes...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

n_gram_range = (1, 3)
#stop_words = "english"

# Extract candidate words/phrases

cv = CountVectorizer(ngram_range=n_gram_range)

In [ ]:
 cv.fit_transform(x).get_feature_names()

In [ ]:
t1 = df.head(1)

In [ ]:
df['content'][1]

'In\xa0supervised\xa0learning,\xa0eac algorithm analyzes the training data and produces an '

In [ ]:
df['content'] = df['content'].astype('string')

In [ ]:
df.dtypes

title      object
content    string
dtype: object

In [ ]:
df['content'][0]

'\xa0Supervised\xa0learning\xa0is\xa0the\xa0machine\xa0learning\xa0task\xa0of\xa0\xa0learning\xa0a\xa0function\xa0that\xa0maps\xa0an\xa0input\xa0to\xa0an\xa0output\xa0based\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0on\xa0example\xa0input-output\xa0pairs.'

In [ ]:
[df['content'][0]]

['\xa0Supervised\xa0learning\xa0is\xa0the\xa0machine\xa0learning\xa0task\xa0of\xa0\xa0learning\xa0a\xa0function\xa0that\xa0maps\xa0an\xa0input\xa0to\xa0an\xa0output\xa0based\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0on\xa0example\xa0input-output\xa0pairs.']

In [ ]:
cv.fit([df['content'][0]]).get_feature_names()

['an input',
 'an output',
 'based on',
 'example input',
 'function that',
 'input output',
 'input to',
 'is the',
 'learning function',
 'learning is',
 'learning task',
 'machine learning',
 'maps an',
 'of learning',
 'on example',
 'output based',
 'output pairs',
 'supervised learning',
 'task of',
 'that maps',
 'the machine',
 'to an']

In [ ]:
#1 
df['cv']  = df['content'].apply(lambda[] x : cv.fit([x]).get_feature_names())

In [ ]:
#2
output1 = [word for word in text if word in ed0_]

In [ ]:
df['cv'] = ""

In [ ]:
df

  title   ...                                           distance
0      a  ...  [an input, an input to, an output, an output b...
1      b  ...  [algorithm analyzes, algorithm analyzes the, a...

[2 rows x 4 columns]

In [ ]:
#3
len(df['cv'][0])

61

In [ ]:
wordsimp = []

In [ ]:
for i in range(len(df['cv'][0])):
  if (len(df['cv'][0][i].split()) ==2):
    wordsimp.extend(df['cv'][0][i].split())

In [ ]:
wordsimp

['an',
 'input',
 'an',
 'output',
 'based',
 'on',
 'example',
 'input',
 'function',
 'that',
 'input',
 'output',
 'input',
 'to',
 'is',
 'the',
 'learning',
 'function',
 'learning',
 'is',
 'learning',
 'task',
 'machine',
 'learning',
 'maps',
 'an',
 'of',
 'learning',
 'on',
 'example',
 'output',
 'based',
 'output',
 'pairs',
 'supervised',
 'learning',
 'task',
 'of',
 'that',
 'maps',
 'the',
 'machine',
 'to',
 'an']

In [ ]:
dictha = {k: v for v, k in enumerate(wordsimp)}
dictha

{'an': 43,
 'based': 31,
 'example': 29,
 'function': 17,
 'input': 12,
 'is': 19,
 'learning': 35,
 'machine': 41,
 'maps': 39,
 'of': 37,
 'on': 28,
 'output': 32,
 'pairs': 33,
 'supervised': 34,
 'task': 36,
 'that': 38,
 'the': 40,
 'to': 42}

In [ ]:
df['cv'][0]

['an',
 'an input',
 'an input to',
 'an output',
 'an output based',
 'based',
 'based on',
 'based on example',
 'example',
 'example input',
 'example input output',
 'function',
 'function that',
 'function that maps',
 'input',
 'input output',
 'input output pairs',
 'input to',
 'input to an',
 'is',
 'is the',
 'is the machine',
 'learning',
 'learning function',
 'learning function that',
 'learning is',
 'learning is the',
 'learning task',
 'learning task of',
 'machine',
 'machine learning',
 'machine learning task',
 'maps',
 'maps an',
 'maps an input',
 'of',
 'of learning',
 'of learning function',
 'on',
 'on example',
 'on example input',
 'output',
 'output based',
 'output based on',
 'output pairs',
 'pairs',
 'supervised',
 'supervised learning',
 'supervised learning is',
 'task',
 'task of',
 'task of learning',
 'that',
 'that maps',
 'that maps an',
 'the',
 'the machine',
 'the machine learning',
 'to',
 'to an',
 'to an output']

In [ ]:
dictha.keys()

dict_keys(['an', 'input', 'output', 'based', 'on', 'example', 'function', 'that', 'to', 'is', 'the', 'learning', 'task', 'machine', 'maps', 'of', 'pairs', 'supervised'])

In [ ]:
[word for word in df['cv'][0] if word not in dictha.keys()]

['c', 'v']

In [ ]:
df['cv']

0                                             (an, 43)
1    [algorithm, algorithm analyzes, algorithm anal...
Name: cv, dtype: object

In [ ]:
[word for word in df['distance'][0] if word not in wordsimp]

In [ ]:
%%timeit
df['distance'].apply(lambda x : [word for word in x if word not in  wordsimp])

1000 loops, best of 5: 222 µs per loop

In [ ]:
list1 = 'apple'
str2 = 'people'
list2 = ['apple', 'oragne','pineapple']

In [ ]:
list1,str2 in list2

NameError: ignored

In [ ]:
%%timeit
df['distance'].apply(lambda x : [word for word in x if word not in  dictha.keys()])

10000 loops, best of 5: 180 µs per loop

In [ ]:
df['distance'][0]

['an input',
 'an input to',
 'an output',
 'an output based',
 'based on',
 'based on example',
 'example input',
 'example input output',
 'function that',
 'function that maps',
 'input output',
 'input output pairs',
 'input to',
 'input to an',
 'is the',
 'is the machine',
 'learning function',
 'learning function that',
 'learning is',
 'learning is the',
 'learning task',
 'learning task of',
 'machine learning',
 'machine learning task',
 'maps an',
 'maps an input',
 'of learning',
 'of learning function',
 'on example',
 'on example input',
 'output based',
 'output based on',
 'output pairs',
 'supervised learning',
 'supervised learning is',
 'task of',
 'task of learning',
 'that maps',
 'that maps an',
 'the machine',
 'the machine learning',
 'to an',
 'to an output']

In [ ]:
#속도줄이기 vectorizer
def reomovein2words(tt):
  wordsimp = []
  for i in range(len(tt)):
    if len(tt[i].split()) ==2:
      wordsimp.extend(tt[i].split())
      wordsimp = list(set(wordsimp))
  return [word for word in tt if word not in wordsimp]

In [ ]:
#3

#df['distance'] = reomovein2words(df['cv'])
df['distance'] = df['cv'].apply(lambda row: reomovein2words(row))

In [ ]:
df

  title   ...                                           distance
0      a  ...  [an input, an input to, an output, an output b...
1      b  ...  [algorithm analyzes, algorithm analyzes the, a...

[2 rows x 4 columns]

In [ ]:
reomovein2words(ttt)

['an input',
 'an input to',
 'an output',
 'an output based',
 'based on',
 'based on example',
 'example input',
 'example input output',
 'function that',
 'function that maps',
 'input output',
 'input output pairs',
 'input to',
 'input to an',
 'is the',
 'is the machine',
 'learning function',
 'learning function that',
 'learning is',
 'learning is the',
 'learning task',
 'learning task of',
 'machine learning',
 'machine learning task',
 'maps an',
 'maps an input',
 'of learning',
 'of learning function',
 'on example',
 'on example input',
 'output based',
 'output based on',
 'output pairs',
 'supervised learning',
 'supervised learning is',
 'task of',
 'task of learning',
 'that maps',
 'that maps an',
 'the machine',
 'the machine learning',
 'to an',
 'to an output']

In [ ]:
ttt = df['cv'][0]
ttt

['an',
 'an input',
 'an input to',
 'an output',
 'an output based',
 'based',
 'based on',
 'based on example',
 'example',
 'example input',
 'example input output',
 'function',
 'function that',
 'function that maps',
 'input',
 'input output',
 'input output pairs',
 'input to',
 'input to an',
 'is',
 'is the',
 'is the machine',
 'learning',
 'learning function',
 'learning function that',
 'learning is',
 'learning is the',
 'learning task',
 'learning task of',
 'machine',
 'machine learning',
 'machine learning task',
 'maps',
 'maps an',
 'maps an input',
 'of',
 'of learning',
 'of learning function',
 'on',
 'on example',
 'on example input',
 'output',
 'output based',
 'output based on',
 'output pairs',
 'pairs',
 'supervised',
 'supervised learning',
 'supervised learning is',
 'task',
 'task of',
 'task of learning',
 'that',
 'that maps',
 'that maps an',
 'the',
 'the machine',
 'the machine learning',
 'to',
 'to an',
 'to an output']

In [ ]:
df

#keyword extraction (n gram)

In [ ]:
ed0_ = set(ed[0]['keywords_df'].keys())

In [ ]:
len(eng)

251

In [ ]:
eng0 = set(eng[0]['keywords_df'].keys())

In [ ]:
for i in range(len(eng)):
  edi = set(eng[i]['keywords_df'].keys())
  eng0.update(edi)

In [ ]:
len(eng0)

668901

In [ ]:
stopwords

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))
new_words = ["using", "show", "result", "large", "also", "iv", "one", "two", "new", "previously", "shown"]
stop_words = stop_words.union(new_words)
nltk.download('wordnet') 
from nltk.stem.wordnet import WordNetLemmatizer
#stop_words

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.

In [ ]:
doc = """
         Hwang Soon-won started his literary career as a poet. He had run twenty two poems on literary journals and issued two collections of poems before publishing his first short story. His career as a poet has been taken importantly by the researches which studied his short stories. As a result of such an interest, many papers have insisted that lyricism is an individual characteristic of his short stories. But lyrical character is not appropriated by his short stories. Short story as a genre generally contains lyricism. So those papers made a mistake that took a general matter as a special. I project this paper from critical review to those papers. And I propose ‘magical transcendence’ and ‘pictorial narrative’ as two characteristics of his short stories.
The magical effect of folktale functions as an main structural element in his short stories. In the case of any folktale not to be cited, the magical effect as an episode or a constituting principle, serves to narrative. some characters in his short stories, regard a real experience as a magical phenomenon, try to transcend torment of real life with the help of magic. In some cases, the narrative of his text are plotted according to the process of magical rite. Magical transcendence is the name which this paper use to call such phenomena. The technique which substitutes impressive scene for narration, is frequently used in his short stories. I I call pictorial narrative the phenomenon that narrative process converges to such a scene.
Lyricism is difficult to be used in an objective copy to reality, because it tends to head for subject. Hwang Soon-won’s short stories are no exception for this problem of realism. He copies not objective reality but the characters’ subjective attitude to the reality. The attitude goes from humanitarianism and endurance to nihilism.
      """

In [ ]:
text = doc.lower()
import re
#remove tags
text=re.sub("&lt;/?.*?&gt;"," &lt;&gt; ",text)

# remove special characters and digits
text=re.sub("(\\d|\\W)+"," ",text)

##Convert to list from string
text = text.split()

##Stemming
#ps=PorterStemmer()
#Lemmatisation
#lem = WordNetLemmatizer()
#text = [lem.lemmatize(word) for word in text if not word in  
        #stop_words] 
#text = " ".join(text)
#corpus.append(text)

In [ ]:
output1 = [word for word in text if word in eng0]

In [ ]:
output1

['hwang',
 'career',
 'as',
 'a',
 'poet',
 'he',
 'had',
 'run',
 'on',
 'journals',
 'collections',
 'publishing',
 'first',
 'short',
 'story',
 'career',
 'as',
 'a',
 'poet',
 'researches',
 'short',
 'stories',
 'as',
 'a',
 'result',
 'an',
 'interest',
 'papers',
 'is',
 'an',
 'individual',
 'characteristic',
 'short',
 'stories',
 'character',
 'is',
 'short',
 'stories',
 'short',
 'story',
 'as',
 'a',
 'genre',
 'contains',
 'papers',
 'a',
 'mistake',
 'a',
 'general',
 'matter',
 'as',
 'a',
 'i',
 'project',
 'paper',
 'critical',
 'review',
 'papers',
 'i',
 'transcendence',
 'pictorial',
 'narrative',
 'as',
 'characteristics',
 'short',
 'stories',
 'effect',
 'functions',
 'as',
 'an',
 'main',
 'structural',
 'element',
 'in',
 'short',
 'stories',
 'in',
 'case',
 'effect',
 'as',
 'an',
 'episode',
 'or',
 'a',
 'principle',
 'narrative',
 'characters',
 'in',
 'short',
 'stories',
 'a',
 'real',
 'experience',
 'as',
 'a',
 'phenomenon',
 'try',
 'transcend',
 'real',
 'life',
 'help',
 'magic',
 'in',
 'narrative',
 'text',
 'are',
 'process',
 'rite',
 'transcendence',
 'is',
 'name',
 'paper',
 'use',
 'call',
 'phenomena',
 'technique',
 'substitutes',
 'scene',
 'narration',
 'is',
 'in',
 'short',
 'stories',
 'i',
 'i',
 'call',
 'pictorial',
 'narrative',
 'phenomenon',
 'narrative',
 'process',
 'a',
 'scene',
 'is',
 'difficult',
 'in',
 'an',
 'objective',
 'copy',
 'reality',
 'it',
 'head',
 'subject',
 'hwang',
 's',
 'short',
 'stories',
 'are',
 'no',
 'exception',
 'problem',
 'realism',
 'he',
 'copies',
 'objective',
 'reality',
 'characters',
 'subjective',
 'attitude',
 'reality',
 'attitude',
 'endurance']

In [ ]:
len(text)
len(output1)

73

#n_gram

In [ ]:
text = doc.lower()
import re
#remove tags
text=re.sub("&lt;/?.*?&gt;"," &lt;&gt; ",text)

# remove special characters and digits
text=re.sub("(\\d|\\W)+"," ",text)
text

' hwang soon won started his literary career as a poet he had run twenty two poems on literary journals and issued two collections of poems before publishing his first short story his career as a poet has been taken importantly by the researches which studied his short stories as a result of such an interest many papers have insisted that lyricism is an individual characteristic of his short stories but lyrical character is not appropriated by his short stories short story as a genre generally contains lyricism so those papers made a mistake that took a general matter as a special i project this paper from critical review to those papers and i propose magical transcendence and pictorial narrative as two characteristics of his short stories the magical effect of folktale functions as an main structural element in his short stories in the case of any folktale not to be cited the magical effect as an episode or a constituting principle serves to narrative some characters in his short stories regard a real experience as a magical phenomenon try to transcend torment of real life with the help of magic in some cases the narrative of his text are plotted according to the process of magical rite magical transcendence is the name which this paper use to call such phenomena the technique which substitutes impressive scene for narration is frequently used in his short stories i i call pictorial narrative the phenomenon that narrative process converges to such a scene lyricism is difficult to be used in an objective copy to reality because it tends to head for subject hwang soon won s short stories are no exception for this problem of realism he copies not objective reality but the characters subjective attitude to the reality the attitude goes from humanitarianism and endurance to nihilism '

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

n_gram_range = (2, 2)
#stop_words = "english"

# Extract candidate words/phrases
count = CountVectorizer(ngram_range=n_gram_range).fit([text])
candidates = count.get_feature_names()
candidates

['according to',
 'an episode',
 'an individual',
 'an interest',
 'an main',
 'an objective',
 'and endurance',
 'and issued',
 'and pictorial',
 'and propose',
 'any folktale',
 'appropriated by',
 'are no',
 'are plotted',
 'as an',
 'as genre',
 'as magical',
 'as poet',
 'as result',
 'as special',
 'as two',
 'attitude goes',
 'attitude to',
 'be cited',
 'be used',
 'because it',
 'been taken',
 'before publishing',
 'but lyrical',
 'but the',
 'by his',
 'by the',
 'call pictorial',
 'call such',
 'career as',
 'case of',
 'cases the',
 'character is',
 'characteristic of',
 'characteristics of',
 'characters in',
 'characters subjective',
 'cited the',
 'collections of',
 'constituting principle',
 'contains lyricism',
 'converges to',
 'copies not',
 'copy to',
 'critical review',
 'difficult to',
 'effect as',
 'effect of',
 'element in',
 'endurance to',
 'episode or',
 'exception for',
 'experience as',
 'first short',
 'folktale functions',
 'folktale not',
 'for narration',
 'for subject',
 'for this',
 'frequently used',
 'from critical',
 'from humanitarianism',
 'functions as',
 'general matter',
 'generally contains',
 'genre generally',
 'goes from',
 'had run',
 'has been',
 'have insisted',
 'he copies',
 'he had',
 'head for',
 'help of',
 'his career',
 'his first',
 'his literary',
 'his short',
 'his text',
 'humanitarianism and',
 'hwang soon',
 'importantly by',
 'impressive scene',
 'in an',
 'in his',
 'in some',
 'in the',
 'individual characteristic',
 'insisted that',
 'interest many',
 'is an',
 'is difficult',
 'is frequently',
 'is not',
 'is the',
 'issued two',
 'it tends',
 'journals and',
 'life with',
 'literary career',
 'literary journals',
 'lyrical character',
 'lyricism is',
 'lyricism so',
 'made mistake',
 'magic in',
 'magical effect',
 'magical phenomenon',
 'magical rite',
 'magical transcendence',
 'main structural',
 'many papers',
 'matter as',
 'mistake that',
 'name which',
 'narration is',
 'narrative as',
 'narrative of',
 'narrative process',
 'narrative some',
 'narrative the',
 'no exception',
 'not appropriated',
 'not objective',
 'not to',
 'objective copy',
 'objective reality',
 'of any',
 'of folktale',
 'of his',
 'of magic',
 'of magical',
 'of poems',
 'of real',
 'of realism',
 'of such',
 'on literary',
 'or constituting',
 'paper from',
 'paper use',
 'papers and',
 'papers have',
 'papers made',
 'phenomena the',
 'phenomenon that',
 'phenomenon try',
 'pictorial narrative',
 'plotted according',
 'poems before',
 'poems on',
 'poet has',
 'poet he',
 'principle serves',
 'problem of',
 'process converges',
 'process of',
 'project this',
 'propose magical',
 'publishing his',
 'real experience',
 'real life',
 'realism he',
 'reality because',
 'reality but',
 'reality the',
 'regard real',
 'researches which',
 'result of',
 'review to',
 'rite magical',
 'run twenty',
 'scene for',
 'scene lyricism',
 'serves to',
 'short stories',
 'short story',
 'so those',
 'some cases',
 'some characters',
 'soon won',
 'special project',
 'started his',
 'stories are',
 'stories as',
 'stories but',
 'stories call',
 'stories in',
 'stories regard',
 'stories short',
 'stories the',
 'story as',
 'story his',
 'structural element',
 'studied his',
 'subject hwang',
 'subjective attitude',
 'substitutes impressive',
 'such an',
 'such phenomena',
 'such scene',
 'taken importantly',
 'technique which',
 'tends to',
 'text are',
 'that lyricism',
 'that narrative',
 'that took',
 'the attitude',
 'the case',
 'the characters',
 'the help',
 'the magical',
 'the name',
 'the narrative',
 'the phenomenon',
 'the process',
 'the reality',
 'the researches',
 'the technique',
 'this paper',
 'this problem',
 'those papers',
 'to be',
 'to call',
 'to head',
 'to narrative',
 'to nihilism',
 'to reality',
 'to such',
 'to the',
 'to those',
 'to transcend',
 'took general',
 'torment of',
 'transcend torment',
 'transcendence and',
 'transcendence is',
 'try to',
 'twenty two',
 'two characteristics',
 'two collections',
 'two poems',
 'use to',
 'used in',
 'which studied',
 'which substitutes',
 'which this',
 'with the',
 'won short',
 'won started']

In [ ]:
output2 = [word for word in candidates if word in eng0]

In [ ]:
output2

['critical review',
 'objective reality',
 'short stories',
 'short story',
 'structural element']

In [ ]:
#3 gram ?

In [ ]:
#weight? 
output = output1 + output2 * 2

In [ ]:
output

['learning',
 'is',
 'machine',
 'learning',
 'task',
 'learning',
 'a',
 'function',
 'maps',
 'an',
 'input',
 'an',
 'output',
 'on',
 'example',
 'input',
 'output',
 'pairs',
 'it',
 'a',
 'function',
 'training',
 'data',
 'a',
 'set',
 'training',
 'examples',
 'in',
 'learning',
 'example',
 'is',
 'a',
 'pair',
 'an',
 'input',
 'object',
 'a',
 'vector',
 'a',
 'desired',
 'output',
 'value',
 'supervisory',
 'signal',
 'a',
 'learning',
 'algorithm',
 'training',
 'data',
 'an',
 'function',
 'can',
 'mapping',
 'new',
 'examples',
 'an',
 'optimal',
 'scenario',
 'will',
 'allow',
 'algorithm',
 'class',
 'labels',
 'requires',
 'learning',
 'algorithm',
 'training',
 'data',
 'situations',
 'in',
 'a',
 'see',
 'bias',
 'learning algorithm',
 'learning function',
 'learning task',
 'machine learning',
 'supervised learning',
 'training data',
 'training examples',
 'learning algorithm',
 'learning function',
 'learning task',
 'machine learning',
 'supervised learning',
 'training data',
 'training examples']

#Inner join

#분야 임베딩

In [ ]:
#사전키워드메트릭스

In [ ]:
#ed = pd.read_pickle('clarivate_dictionary_v1.pickle')
df = pd.DataFrame()
for i in range(0, len(ed)):
        t = pd.DataFrame(ed[i]).reset_index()
        df = df.append(t)

In [ ]:
field_matrix_by_keyword = df[['index', 'subject', 'keywords_tfidf']]
field_matrix_by_keyword = pd.pivot_table(field_matrix_by_keyword, index = 'index', columns = 'subject', values = 'keywords_tfidf', fill_value=0).reset_index()
field_matrix_by_keyword

subject                                 index  ...  Zoology
0                              " sylvia plath  ...      0.0
1                          " xmlns:mml="http:  ...      0.0
2        "1-methyl-1-phenyl-2-neopentylsilene  ...      0.0
3                     "a" determinant mutants  ...      0.0
4                      "a" determinant region  ...      0.0
...                                       ...  ...      ...
668881                {110}<001> goss texture  ...      0.0
668882         {112} incoherent twin boundary  ...      0.0
668883                            {311} facet  ...      0.0
668884              {411} < 148 > orientation  ...      0.0
668885                            |b-1| field  ...      0.0

[668886 rows x 252 columns]

In [ ]:
text_mat = pd.DataFrame({
    'Text' :'text',
    'keyword' : output
}).groupby(['Text', 'keyword']).size().reset_index(name='counts')

In [ ]:
text_mat = text_mat.rename(columns={'keyword': 'index'})

In [ ]:
field_matrix_by_course = pd.merge(text_mat,field_matrix_by_keyword,  # 다전공 + 과목 + 키워드 메트릭스 병합
                on = 'index',
                how = 'inner')
field_matrix_by_course

   Text             index  counts  ...  Water Resources  Women's Studies   Zoology
0  text         algorithm       3  ...         5.646496              0.0  0.256659
1  text  machine learning       2  ...         2.079572              0.0  0.000000
2  text            output       3  ...         0.614344              0.0  0.000000
3  text             pairs       1  ...         0.000000              0.0  0.000000
4  text            signal       1  ...         0.335216              0.0  0.335216
5  text            vector       1  ...         0.000000              0.0  1.072702

[6 rows x 254 columns]

In [ ]:
#wieght?
for i in range(251):
  field_matrix_by_course.iloc[:,i+3] = field_matrix_by_course['counts'] *  field_matrix_by_course.iloc[:,i+3]

In [ ]:
field_matrix_by_course

   Text             index  counts  ...  Water Resources  Women's Studies   Zoology
0  text         algorithm       3  ...        16.939489              0.0  0.769977
1  text  machine learning       2  ...         4.159143              0.0  0.000000
2  text            output       3  ...         1.843032              0.0  0.000000
3  text             pairs       1  ...         0.000000              0.0  0.000000
4  text            signal       1  ...         0.335216              0.0  0.335216
5  text            vector       1  ...         0.000000              0.0  1.072702

[6 rows x 254 columns]

In [ ]:
field_matrix_by_course = field_matrix_by_course.groupby('Text').mean().reset_index()                        
field_matrix_by_course

   Text    counts  Acoustics  ...  Water Resources  Women's Studies   Zoology
0  text  1.833333   3.292886  ...          3.87948              0.0  0.362982

[1 rows x 253 columns]

#분야 + 단어 임베딩

In [ ]:
field_matrix_by_keyword = pd.pivot_table(text_mat, index = 'Text', columns = 'index', values = 'counts', fill_value=0).reset_index()
field_matrix_by_keyword

index  Text  algorithm  machine learning  output  pairs  signal  vector
0      text          3                 2       3      1       1       1

In [ ]:
text_mat

   Text             index  counts
0  text         algorithm       3
1  text  machine learning       2
2  text            output       3
3  text             pairs       1
4  text            signal       1
5  text            vector       1

In [ ]:
df = pd.merge(field_matrix_by_keyword,field_matrix_by_course,  # 분야 + 키워드 메트릭스 병합
                on = 'Text',
                how = 'inner')
df

   Text  algorithm  ...  Women's Studies   Zoology
0  text          3  ...              0.0  0.362982

[1 rows x 259 columns]

In [ ]:
df.T.iloc[1:].sort_values(by = [0]).tail(10)

                                                        0
Instruments & Instrumentation                     17.4987
Operations Research & Management Science          18.7492
Radiology, Nuclear Medicine & Medical Imaging     19.3327
Materials Science, Multidisciplinary              23.1167
Computer Science, Interdisciplinary Applications  24.5529
Physics, Applied                                  27.5575
Computer Science, Artificial Intelligence          29.984
Computer Science, Information Systems             33.3789
Telecommunications                                38.3393
Engineering, Electrical & Electronic              101.695

In [ ]:
#반응형

#반응형

In [ ]:
#추출된 논문 가운데 돌려서 도출

In [ ]:
키워드에서 빼거나 
분야에서 빼거나